/*
 * Do not edit this file manually.
 * Update this file by ./options_lister.js
*/
module.exports ={
	"lang": "lang",
	"write_object_tree": "write_object_tree",
	"object_tree_path": "object_tree_path",
	"write_logs": "write_logs",
	"log_path": "log_path",
	"verbose": "verbose",
	"enable_default_ignore_paths": "enable_default_ignore_paths",
	"ignore_paths": "ignore_paths",
	"ignore_objects": "ignore_objects",
	"package_json_path": "package_json_path",
	"html_path": "html_path",
	"html_template_name": "html_template_name",
	"html_site_title": "html_site_title",
	"html_site_description": "html_site_description",
	"html_notifications": "html_notifications",
	"html_gnavi_links": "html_gnavi_links",
	"html_about_html": "html_about_html",
	"html_version_html": "html_version_html",
	"html_custom_css": "html_custom_css",
	"html_custom_script": "html_custom_script",
	"html_meta": {
		"keywords": "html_meta.keywords",
		"description": "html_meta.description",
		"author": "html_meta.author",
		"og_site_name": "html_meta.og_site_name",
		"og_url": "html_meta.og_url",
		"og_image": "html_meta.og_image",
		"custom_html": "html_meta.custom_html"
	},
	"html_format": {
		"lang": "html_format.lang",
		"g_navi": "html_format.g_navi",
		"documentation": "html_format.documentation",
		"g_navi_list": "html_format.g_navi_list",
		"notifications": "html_format.notifications",
		"item": "html_format.item",
		"item_name": "html_format.item_name",
		"item_description": "html_format.item_description",
		"item_details": "html_format.item_details",
		"item_details_item": "html_format.item_details_item",
		"item_details_datatypes": "html_format.item_details_datatypes",
		"item_details_datatype": "html_format.item_details_datatype",
		"example_wrap": "html_format.example_wrap",
		"example": "html_format.example",
		"example_caption": "html_format.example_caption",
		"link": "html_format.link"
	}
}