/*
 * Do not edit this file manually.
 * Update this file by ./options_lister.js
*/
module.exports ={
	"lang": "lang",
	"write_object_tree": "write_object_tree",
	"object_tree_path": "object_tree_path",
	"write_logs": "write_logs",
	"log_path": "log_path",
	"trail_tag": "trail_tag",
	"verbose": "verbose",
	"enable_default_ignore_paths": "enable_default_ignore_paths",
	"ignore_paths": "ignore_paths",
	"ignore_objects": "ignore_objects",
	"package_json_path": "package_json_path",
	"user_comments": "user_comments",
	"html_template_name": "html_template_name",
	"html_site_title": "html_site_title",
	"html_site_description": "html_site_description",
	"html_gnavi_links": "html_gnavi_links",
	"html_notifications": "html_notifications",
	"html_about_html": "html_about_html",
	"html_version_html": "html_version_html",
	"html_custom_css": "html_custom_css",
	"html_custom_script": "html_custom_script",
	"html_meta": "html_meta",
	"html_format": "html_format"
}